### PR TITLE
Thermo parse

### PR DESCRIPTION
**Pull request by SylvainPlessis**
graph
### Common part
This is one PR of a bunch of PRs to finalize parsing, thermodynamics and transport.  There will be several PRs, the only thing missing now is the merging with *master*, which will come once the setup of the PRs is made.  To make things as clear as I can, all the PRs will have a common section showing the graph with a star to mark the current PR.
```
xml_parser <-- input_parsing_format <-- ascii_parser   <-- species_parsing <-- \
                                                                                \
NASA polynomials <-- UnifiedThermo <---------------------------------------------- thermo_parsing * <--
                                     \                                                                  \
transport_new <------------------------  transport_thermo <--------------------------------------------- transport_thermo_parser
```
So here is the parser/thermo/transport bunch of PR.  There are also two more PRs, the ```opt_transport``` and the ```almost_Exact```. 
The ```opt_transport``` merges ```transport_thermo_parser``` with ```conditions_reac```, which enables to pass a ```KineticsConditions<StateType,VectorStateType>``` object instead of temperature, which translates into computing once and for all the ```TempCache<StateType>``` object instead of locally where it's needed.
```almost_Exact``` takes in the ```kin_reset```.

### This PR

It is the thermodynamics parsing for all the parsers, with the latest version of the thermo.

### CODE REVIEW

**Comment by pbauman** [comment]
Sylvain, can you merge master here? Looks like the conflics/changes could be significant.

**Comment by SylvainPlessis** [comment]
No I can't.  This is built on the obsolete PR #79, I don't want unwanted features to come back in (or anything weird even not `dangerous').  I'll git cherry-pick or find something else, but I will not merge all that history...

**Comment by SylvainPlessis** [comment]
my bad, I was wrong, I'll merge it… I have no excuse, I'm the one who made the graph...

**Comment by SylvainPlessis** [comment]
That was one big merging issue...
Let's try to be brief:
  - there was the update template v/s base object to adapt, it gave its little problem on its own,
  - all the backward compatibility stuff, there are two levels, cea v/s nasa and file names, ascii_parsing v/s _parsing.

This explains the size of this merge.

**Comment by pbauman** [comment]
Yeah, that's why I didn't want to touch this one. I'll take a look tonight.

**Comment by roystgnr** [comment]
Passes VexCL+MetaPhysicL+GRINS+FIN-S tests.  I'm okay to merge.

**Comment by pbauman** [comment]
Awesome. Onward!

**Pull request merged**
