### PR TITLE
Stockmayer/extrapolation

### PR DESCRIPTION
**Pull request by SylvainPlessis**
This is another feature, basically in case the requested temperature is higher than the maximum temperature of the Stockmayer potential (lowest I'm aware is 3,800 K for H2).  We provide an extrapolation in T^{1/6} outside this range.

In the case of required extrapolation, the user needs to provide an upper bound.

### CODE REVIEW

**Comment by pbauman** [comment]
Is this critically related to the other PRs?

**Comment by SylvainPlessis** [comment]
No, this is the first of a few PR (I swear, a few with very little changes) to upgrade Antioch's capacities.

**Comment by SylvainPlessis** [comment]
By the way, it's not related in the way a new tag could (should?) be put before this PR is merged.  It adds a better check for kinetics theory modeling, but no new things.

The conflict is in the _src/Makefile.am_, nothing serious, I'll merge just before we merge it back to master, to avoid possible multiple merging.

**Comment by roystgnr** [comment]
If it's that simple, just rebase?  The less I have to fiddle with stuff that you might fiddle with differently, the more confident I am in my test runs.

**Comment by SylvainPlessis** [comment]
rebased

**Comment by pbauman** [comment]
Here's the error from Travis:

```
 CXX    Stockmayer_unit.o
Stockmayer_unit.C: In function ‘int tester()’:
Stockmayer_unit.C:110:3: error: ‘read_transport_species_data_ascii’ is not a member of ‘Antioch’
make[3]: *** [Stockmayer_unit.o] Error 1
```

**Comment by SylvainPlessis** [comment]
Yes I'm on it, it's basically updating the Stockmayer test to the parsing.  This error is because the needed file is no more included in Antioch file, but I'm just using the latest version of the parsing.

**Comment by roystgnr** [comment]
Stupid nitpick: could we lower-case Stockmayer in filenames, for consistency with our other files?

**Comment by roystgnr** [comment]
Likewise with Lennard, Jones, etc.

**Comment by pbauman** [comment]
Thanks for catching that. That would've tripped my OCD meter as well had I paid better attention.

**Comment by roystgnr** [comment]
Diffs look good to me (other than the caps), and this passes all my tests.

**Comment by roystgnr** [comment]
Good to merge after we fix up caps issues and tag master.

**Comment by pbauman** [comment]
I've created a 0.3.0-release branch. Merging this.

(Though technically we didn't need to wait since we can branch from whatever hash we want.)

**Pull request merged**
