### PR TITLE
xml_parser GRI30 compatible

### PR DESCRIPTION
**Pull request by SylvainPlessis**
not tested yet, it *should* work.

No test yet, but as it's starting to get a little late here, I'm putting it here anyway, so it's at least testable.

So far I've only checked that it doesn't break anything (at least on my computer, let's see what Travis thinks).

Feel free to add the test if you have the time/will.

Edit: And of course, I've forgotten to link it to the issue.

This is the answer to issue #211

### CODE REVIEW

**Comment by SylvainPlessis** [comment]
tested and approuved by my computer.  Basically, all the falloff reactions in the file *test/input_files/test_parsing.xml* are doubled to fit the GRI way of falloff, and the test accordingly updated.

Good night!

**Comment by roystgnr** [comment]
Some of these tests are actually failing under the hood, but the failures are being masked because ```if(error > tol) scream_and_die();``` is a no-op for ```error==NaN```.

Reactions 0028bis, 0029bis, 0030bis, 0031bis, 0032bis, 0033bis, and 0034bis are all outputting NaN because alpha, T1, and T3 have been left set to 0, and T2 has been left set to 1e50.

Reaction 0035 is failing, but in that case I'm not sure why.

I can set up a PR that reproduces the failures if it would help.

**Comment by roystgnr** [comment]
Looks like those bis reactions are returning parser->Troe() == false, so they're not querying the Troe parameters in the first place.

**Comment by roystgnr** [comment]
And in turn that's because rate_constant() is looking for a Troe subsection but isn't looking for a falloff subsection of type Troe.

**Comment by roystgnr** [comment]
Merging and rebasing on #228 fixes all the bis reactions for me.  Now to look into 0035.

**Comment by roystgnr** [comment]
0035 is a photochemistry problem, apparently not a parsing problem.

**Comment by roystgnr** [comment]
And 0035 is fixed for me in #229.  I'm *loving* the new regression test; thanks @SylvainPlessis

**Pull request merged**
