### PR TITLE
Opt vis

### PR DESCRIPTION
**Pull request by SylvainPlessis**
Supersedes PR #101, this one being actually branched off master instead of wilke_approx.

Small and self explanatory I think.

### CODE REVIEW

**Comment by pbauman** [comment]
Have you timed the speed up yet, just for giggles?

**Comment by SylvainPlessis** [comment]
5 times faster for the Exact computations, full application scale (transport + kin).

**Comment by SylvainPlessis** [comment]
Na, 20% speedup, there is a factor 5, but not quite at this place….

**Comment by roystgnr** [comment]
Looks good.  :+1:  Do we have any application regression test coverage for the new algorithm, or just the antioch tests?

**Comment by SylvainPlessis** [comment]
We can use the ExacT code.  Last time I've checked, we were still agreeing.

**Comment by pbauman** [comment]
Awesome!

**Pull request merged**
