### PR TITLE
Nasa polynomials

### PR DESCRIPTION
**Pull request by SylvainPlessis**
graph

Here is the thermo PR.

I'm not fully happy with the thermo, but I'm not sure how exactly a nice general thermo module should look like.  To start with the not very nice thing, cea and nasa polynomials have differerent expressions and the nasa can have custom temperature intervals.  So when the cea is fully described and only the coefficients are needed (thus one ```vector<CoeffType>``` needed in constructor), a nasa polynomials requires the temperatures and the coefficients (thus two ```vector<CoeffType>``` in constructor).  So nasa and cea have the two constructors for compatibility.  There is thus a default for the temperature interval for the nasa polynomials, and a very ineleguant constructor for the cea, only for compatibility purposes.

The test has been extended also to test for all thermo quantities.

### CODE REVIEW

**Comment by pbauman** [comment]
OK, before digging into the code, I'm just trying to compile GRINS against this. It does not compile which means it's not backward compatible. CEAThermoMixture is gone - we need a shim for this. Also looks like CEAEvaluator is gone - we need a shim for this.

It both instances, what are you proposing as replacements? We we last talked, I thought that we were keeping CEA as a specilization of NASA9 since CEA is a particular incarnation of NASA9 (defined temperature intervals).

**Comment by SylvainPlessis** [comment]
They're supposed to be there in the form given in my note of the 11th December.  The files ```cea_mixture.h``` and ```cea_evaluator.h``` are this.

What exactly is wrong?

**Comment by pbauman** [comment]
Compiler complained `CEAMixture` and `CEAEvaluator` were not in Antioch namespace. I won't be able to take a closer look until later.

**Comment by pbauman** [comment]
`cea_mixture.h` only had NASA9 things.

**Comment by SylvainPlessis** [comment]
Alright, so if I understand properly, you need something along the line of
```
template<typename CoeffType>
class CEACurveFit:public NASA9<CoeffType>
{
   constructor throw a antioch_deprecated()
}
```
And it does not exist, is that right?

**Comment by pbauman** [comment]
Correct that it does not exist.

But I also thought were weren't deprecating CEA (except CEAThermodynamics). My thinking, and correct me if I'm wrong, was the NASA9 was the polynomial form, but did not dictate the temperature intervals (you could do whatever) where as CEA is a NASA9 polynomial, BUT also has prescribed temperature intervals. So, we have NASA9 polynomials which take temperature intervals and whatever in the constructor and we have CEA which subclasses NASA9 and prescribes the temperature intervals in the constructor.

**Comment by SylvainPlessis** [comment]
Well actually I did not found a custom NASA9, the custom temperature intervals are (to my knowledge, which can be wrong) special cases of NASA7.  I'm wondering, at that level, wouldn't it be better to have a ```NASA<CoeffType, int D>``` where the temperature intervals are custom and the polynomials are throwing ```antioch_error()``` and then implement strictly the polynomial in ```NASA<CoeffType,9>``` and ```NASA<CoeffType,7>```, and then have the ```CEACurveFit<CoeffType>``` be the über specialization.

I just had this idea, and I think it's much better than all the others I had.  What about it?

**Comment by pbauman** [comment]
Swap NASA9 for NASA7 then in my comments above. I don't see any reason to template around the number of terms - is there some compelling reason?

**Comment by SylvainPlessis** [comment]
I don't have to rewrite the constructor for custom temperature intervals, be them with 9 parameters (that's the CEA case), or 7 parameters (that's the ChemKin input files case).

**Comment by SylvainPlessis** [comment]
Also, to answer the question "If you haven't found custom NASA9 temperature intervals, why do it?", I'd say: "Never trust chemists with a computer!"

**Comment by SylvainPlessis** [comment]
Alright the backward computability should be here, I've tried to put the discussion in the comments before the ```CEACurveFit<CoeffType>``` object, so we know what happened, could happen, may happen.

**Comment by pbauman** [comment]
Still missing:

`In file included from ../../../../pbauman/src/properties/include/grins/antioch_evaluator.h:34:0,
                 from ../../../../pbauman/src/properties/include/grins/antioch_wilke_transport_evaluator.h:34,
                 from ../../../../pbauman/src/physics/src/physics_factory.C:77:
../../../../pbauman/src/properties/include/grins/antioch_mixture.h:65:11: error: 'CEAThermoMixture' in namespace 'Antioch' does not name a type
     const Antioch::CEAThermoMixture<libMesh::Real>& cea_mixture() const;`

`
In file included from ../../../../pbauman/src/properties/include/grins/antioch_evaluator.h:35:0,
                 from ../../../../pbauman/src/properties/include/grins/antioch_wilke_transport_evaluator.h:34,
                 from ../../../../pbauman/src/physics/src/physics_factory.C:77:
../../../../pbauman/src/properties/include/grins/antioch_kinetics.h:67:5: error: 'CEAEvaluator' in namespace 'Antioch' does not name a type
     Antioch::CEAEvaluator<libMesh::Real> _antioch_cea_thermo;`

**Comment by SylvainPlessis** [comment]
Holy crap! I know what's wrong, the change from CEA to NASA9 was made at all levels...

**Comment by SylvainPlessis** [comment]
Should work now

**Comment by pbauman** [comment]
Make check is now broken (may be more than the example below):

```
CXX      nasa_evaluator_unit.o
../../../pbauman/test/nasa_evaluator_unit.C: In function ‘int tester(const std::string&)’:
../../../pbauman/test/nasa_evaluator_unit.C:244: error: ‘NASA9ThermoMixture’ is not a member of ‘Antioch’
../../../pbauman/test/nasa_evaluator_unit.C:244: error: expected primary-expression before ‘>’ token
../../../pbauman/test/nasa_evaluator_unit.C:245: error: ‘cea_mixture’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:246: error: ‘NASA9Evaluator’ is not a member of ‘Antioch’
../../../pbauman/test/nasa_evaluator_unit.C:246: error: expected primary-expression before ‘>’ token
../../../pbauman/test/nasa_evaluator_unit.C:246: error: there are no arguments to ‘thermo’ that depend on a template parameter, so a declaration of ‘thermo’ must be available
../../../pbauman/test/nasa_evaluator_unit.C:246: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../../../pbauman/test/nasa_evaluator_unit.C:337: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:374: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:408: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:442: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:476: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:521: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:596: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:671: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:745: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:819: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C: In function ‘int tester(const std::string&) [with Scalar = double]’:
../../../pbauman/test/nasa_evaluator_unit.C:889:   instantiated from here
../../../pbauman/test/nasa_evaluator_unit.C:244: error: ‘cea_mixture’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:245: error: ‘thermo’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C: In function ‘int tester(const std::string&) [with Scalar = float]’:
../../../pbauman/test/nasa_evaluator_unit.C:891:   instantiated from here
../../../pbauman/test/nasa_evaluator_unit.C:244: error: ‘cea_mixture’ was not declared in this scope
../../../pbauman/test/nasa_evaluator_unit.C:245: error: ‘thermo’ was not declared in this scope
```

**Comment by SylvainPlessis** [comment]
I hate this world…

**Comment by SylvainPlessis** [comment]
passes for me

**Comment by pbauman** [comment]
OK, make check is passing for me again, but still not quite there with GRINS:

```
In file included from /fry1/data/users/pbauman/research/antioch/install/nasa9/include/antioch/cea_mixture.h:35:0,
                 from ../../../../pbauman/src/properties/include/grins/antioch_mixture.h:44,
                 from ../../../../pbauman/src/properties/src/antioch_mixture.C:31:
/fry1/data/users/pbauman/research/antioch/install/nasa9/include/antioch/nasa_mixture.h: In instantiation of 'void Antioch::NASAThermoMixture<CoeffType, NASAFit>::add_curve_fit(const string&, const std::vector<T>&) [with CoeffType = double; NASAFit = Antioch::CEACurveFit<double>; std::string = std::basic_string<char>]':
/fry1/data/users/pbauman/research/antioch/install/nasa9/include/antioch/cea_mixture_ascii_parsing.h:101:3:   required from 'void Antioch::read_cea_mixture_data_ascii(Antioch::CEAThermoMixture<NumericType>&, const string&) [with NumericType = double; std::string = std::basic_string<char>]'
/fry1/data/users/pbauman/research/antioch/install/nasa9/include/antioch/cea_mixture_ascii_parsing.h:122:71:   required from 'void Antioch::read_cea_mixture_data_ascii_default(Antioch::CEAThermoMixture<NumericType>&) [with NumericType = double]'
../../../../pbauman/src/properties/src/antioch_mixture.C:59:71:   required from here
/fry1/data/users/pbauman/research/antioch/install/nasa9/include/antioch/nasa_mixture.h:135:55: error: 'Antioch::NASAEvaluator<double, Antioch::CEACurveFit<double> > evaluator' has incomplete type
     NASAEvaluator<CoeffType,NASAFit> evaluator( *this );
```
I'm trying to pin down the culprit, but feel free to beat me to it.

**Comment by SylvainPlessis** [comment]
Found it:
because late ```cea_mixture.h``` had an ```#include "antioch/cea_evaluator.h"```, as the ```Evaluator``` object is forward declared, I removed the corresponding include in the NASA version.  The ```cea_mixture.h``` file in this branch do not have the include either.

So two possibilities, either the ```cea_mixture.h``` file includes the ```cea_evaluator.h``` just like old times, or the NASA mixture file includes the NASA evaluator file, but in that case, we should delete the forward declaration.

**Comment by pbauman** [comment]
Since we're going for backward compatibility, let us do just like old times.

**Comment by roystgnr** [comment]
Not just for backward compatibility's sake.  nasa_mixture.h is really *using* NASAEvaluator, not just declaring a pointer or reference to one.  It needs the actual header.

That reminds me of an issue I need to add...

**Comment by pbauman** [comment]
I'll spoil Travis CI's surprise:

```
CXX      nasa_evaluator_unit.o
In file included from ../../../pbauman/src/thermo/include/antioch/cea_mixture.h:36:0,
                 from ../../../pbauman/test/nasa_evaluator_unit.C:43:
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:25: error: ‘CEAThermoMixture’ does not name a type
     CEAEvaluator( const CEAThermoMixture<CoeffType>& cea_mixture ):
                         ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:25: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:41: error: expected ‘,’ or ‘...’ before ‘<’ token
     CEAEvaluator( const CEAThermoMixture<CoeffType>& cea_mixture ):
                                         ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h: In constructor ‘Antioch::CEAEvaluator<CoeffType>::CEAEvaluator(int)’:
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:52:58: error: ‘cea_mixture’ was not declared in this scope
         NASAEvaluator<CoeffType,CEACurveFit<CoeffType> >(cea_mixture)
                                                          ^
../../../pbauman/test/nasa_evaluator_unit.C: In instantiation of ‘int tester(const string&) [with Scalar = double; std::string = std::basic_string<char>]’:
../../../pbauman/test/nasa_evaluator_unit.C:889:46:   required from here
../../../pbauman/test/nasa_evaluator_unit.C:246:53: error: no matching function for call to ‘Antioch::CEAEvaluator<double>::CEAEvaluator(Antioch::CEAThermoMixture<double>&)’
   Antioch::CEAEvaluator<Scalar> thermo( cea_mixture );
                                                     ^
../../../pbauman/test/nasa_evaluator_unit.C:246:53: note: candidates are:
In file included from ../../../pbauman/src/thermo/include/antioch/cea_mixture.h:36:0,
                 from ../../../pbauman/test/nasa_evaluator_unit.C:43:
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:5: note: Antioch::CEAEvaluator<CoeffType>::CEAEvaluator(int) [with CoeffType = double]
     CEAEvaluator( const CEAThermoMixture<CoeffType>& cea_mixture ):
     ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:5: note:   no known conversion for argument 1 from ‘Antioch::CEAThermoMixture<double>’ to ‘int’
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:47:9: note: constexpr Antioch::CEAEvaluator<double>::CEAEvaluator(const Antioch::CEAEvaluator<double>&)
   class CEAEvaluator : public NASAEvaluator<CoeffType,CEACurveFit<CoeffType> >
         ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:47:9: note:   no known conversion for argument 1 from ‘Antioch::CEAThermoMixture<double>’ to ‘const Antioch::CEAEvaluator<double>&’
../../../pbauman/test/nasa_evaluator_unit.C: In instantiation of ‘int tester(const string&) [with Scalar = float; std::string = std::basic_string<char>]’:
../../../pbauman/test/nasa_evaluator_unit.C:891:45:   required from here
../../../pbauman/test/nasa_evaluator_unit.C:246:53: error: no matching function for call to ‘Antioch::CEAEvaluator<float>::CEAEvaluator(Antioch::CEAThermoMixture<float>&)’
   Antioch::CEAEvaluator<Scalar> thermo( cea_mixture );
                                                     ^
../../../pbauman/test/nasa_evaluator_unit.C:246:53: note: candidates are:
In file included from ../../../pbauman/src/thermo/include/antioch/cea_mixture.h:36:0,
                 from ../../../pbauman/test/nasa_evaluator_unit.C:43:
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:5: note: Antioch::CEAEvaluator<CoeffType>::CEAEvaluator(int) [with CoeffType = float]
     CEAEvaluator( const CEAThermoMixture<CoeffType>& cea_mixture ):
     ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:51:5: note:   no known conversion for argument 1 from ‘Antioch::CEAThermoMixture<float>’ to ‘int’
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:47:9: note: constexpr Antioch::CEAEvaluator<float>::CEAEvaluator(const Antioch::CEAEvaluator<float>&)
   class CEAEvaluator : public NASAEvaluator<CoeffType,CEACurveFit<CoeffType> >
         ^
../../../pbauman/src/thermo/include/antioch/cea_evaluator.h:47:9: note:   no known conversion for argument 1 from ‘Antioch::CEAThermoMixture<float>’ to ‘const Antioch::CEAEvaluator<float>&’
make[3]: *** [nasa_evaluator_unit.o] Error 1
```

**Comment by SylvainPlessis** [comment]
Any living thing nearby I can brutally kill, resurrect and kill again?

**Comment by pbauman** [comment]
OK! GRINS build and make check passes! Now I'll actually look at the PR. :)

**Comment by pbauman** [comment]
OK, with me.

**Comment by pbauman** [comment]
@roystgnr is going to run it through the other trenches before we merge.

**Comment by roystgnr** [comment]
VexCL and MetaPhysicL are happy.  Paul's already checked GRINS, so I'll just hit FIN-S.

**Comment by roystgnr** [comment]
FIN-S is happy too.

**Pull request merged**
