### PR TITLE
Ascii parser

### PR DESCRIPTION
**Pull request by SylvainPlessis**
graph
### Common part
This is one PR of a bunch of PRs to finalize parsing, thermodynamics and transport.  There will be several PRs, the only thing missing now is the merging with *master*, which will come once the setup of the PRs is made.  To make things as clear as I can, all the PRs will have a common section showing the graph with a star to mark the current PR.
```
xml_parser <-- input_parsing_format <-- ascii_parser * <-- species_parsing <-- \
                                                                                \
NASA polynomials <-- UnifiedThermo <---------------------------------------------- thermo_parsing <--
                                     \                                                                \
transport_new <------------------------  transport_thermo <--------------------------------------------- transport_thermo_parser
```
So here is the parser/thermo/transport bunch of PR.  There are also two more PRs, the ```opt_transport``` and the ```almost_Exact```. 
The ```opt_transport``` merges ```transport_thermo_parser``` with ```conditions_reac```, which enables to pass a ```KineticsConditions<StateType,VectorStateType>``` object instead of temperature, which translates into computing once and for all the ```TempCache<StateType>``` object instead of locally where it's needed.
```almost_Exact``` takes in the ```kin_reset```.

### This PR
This is the parser part, thus what this PR add is the finalization of the structure of the parsing capabilities of Antioch.  It formalizes the three current possibilities, xml, chemkin or ascii free format.  This is the ascii free format.

This format is used for species characteristics (mass, enthalpy of formation @0°C, …).
The structure has an important characteristics for developers: there is no parser base object, so for any new parser, the obligation to implement the correct method will only appear if there is an attempt to parse the wrong thing.  For instance, if a parser has no thermodynamics parsing method implemented, it will show only if a user tries using the parser for thermo.  A base object could avoid this by making all the required methods pure virtual, but as this is the only thing it would do, I did not implement it.
Should we add this?

### CODE REVIEW

**Comment by pbauman** [comment]
@SylvainPlessis so I'm going to merge from master because the rebase is too scary at this point (and, frankly, I think I've decided merging > rebasing), but there are 4 add/add conflicts. Meaning the file is being added here and has already been added to master. So, I need to you to tell me for each of the following files if the one in master is the correct one or the one in this PR is the correct one:

chemkin_parser.h
parsing_enum.h
read_reaction_set_data.h
xml_parser.h

**Comment by SylvainPlessis** [comment]
Do you want the explanations or just go with an answer?

chemkin_parser.h, master and only master, no compromise at all

**Comment by pbauman** [comment]
> Do you want the explanations or just go with an answer?

Just the answer. I'll dig into the PR more once master is merged.

> chemkin_parser.h, master and only master, no compromise at all

Master for all or are you just answering for chemkin_parser.h?

**Comment by SylvainPlessis** [comment]
parsing_enum.h : HEAD

I'll go file by file

**Comment by SylvainPlessis** [comment]
read_reaction_set_data.h : master

**Comment by SylvainPlessis** [comment]
xml_parser.h : HEAD

**Comment by SylvainPlessis** [comment]
Should be clean, it's the union of the two, typically one between HEAD and master has an empty line where the other has stuff.

**Comment by pbauman** [comment]
OK, I'm going open a new PR with the merge from master.

**Pull request merged**
