### PR TITLE
Ascii parser

### PR DESCRIPTION
**Pull request by pbauman**
Replaces #87. Just merged from the latest master.

### CODE REVIEW

**Comment by roystgnr** [comment]
Works with MetaPhysicL and VexCL.  Running app tests now.

**Comment by roystgnr** [comment]
Diffs look reasonable too.

**Comment by roystgnr** [comment]
Passes with GRINS and FIN-S for me.  :+1:

**Comment by pbauman** [comment]
Cool, good with me too.

**Pull request merged**
