### PR TITLE
Species parsing

### PR DESCRIPTION
**Pull request by SylvainPlessis**
graph
### Common part
This is one PR of a bunch of PRs to finalize parsing, thermodynamics and transport.  There will be several PRs, the only thing missing now is the merging with *master*, which will come once the setup of the PRs is made.  To make things as clear as I can, all the PRs will have a common section showing the graph with a star to mark the current PR.
```
xml_parser <-- input_parsing_format <-- ascii_parser <-- species_parsing * <-- \
                                                                                \
NASA polynomials <-- UnifiedThermo <---------------------------------------------- thermo_parsing <--
                                     \                                                                \
transport_new <------------------------  transport_thermo <--------------------------------------------- transport_thermo_parser
```
So here is the parser/thermo/transport bunch of PR.  There are also two more PRs, the ```opt_transport``` and the ```almost_Exact```. 
The ```opt_transport``` merges ```transport_thermo_parser``` with ```conditions_reac```, which enables to pass a ```KineticsConditions<StateType,VectorStateType>``` object instead of temperature, which translates into computing once and for all the ```TempCache<StateType>``` object instead of locally where it's needed.
```almost_Exact``` takes in the ```kin_reset```.

### This PR

The species list is parseable by everyone.  The main changes is certainly the names of the files, there is no more reason now to keep the _ascii_ in the name, this is the biggest change.

### CODE REVIEW

**Comment by SylvainPlessis** [comment]
Alright updated to change templates to base class, it should be ok.  PR #111 should be no more needed.

**Comment by roystgnr** [comment]
You're missing parser_base.h in pkginclude_HEADERS in src/Makefile.am

**Comment by roystgnr** [comment]
Functions in headers need to either be declared inline or inside class definitions (thus implicitly inline).  Otherwise it's easy to end up with lots of duplicate symbols at link time, as I'm seeing now.  I'll prepare a PR to pull into your branch.

**Comment by roystgnr** [comment]
Gah.  I was all in favor of making antioch_version() inline to make us header-only, but I didn't notice that we'd also made our TinyXML2 import into a header.  That's going too far IMHO.  I won't futz with it now though.

**Comment by roystgnr** [comment]
This passes all my tests now.  Ready to merge if @pbauman is happy.

**Comment by pbauman** [comment]
Looks good!

**Pull request merged**
