### PR TITLE
Factor out some implementations

### PR DESCRIPTION
**Pull request by pbauman**
Thus, Antioch will no longer be header only. This is primarily to facilitate a PIMPL idiom for the `GSLSpliner` (forthcoming), but I'm hoping this will have the nice side effect of allowing us to have Travis test with VexCL enabled again since we moved several thousand lines of code into .C files that otherwise won't be compiled in tests (only linked in).

Following this PR, users will need to start linking against `libantioch.so` (or `libantioch.a` or `libantioch.la` as the case may be) thus breaking backward compatibility.

I should note that the last commit (62795c1) is a monster --- it didn't occur to me until after I squashed all the commits together that I could've just left all the `#include`'s alone in the headers and factored out the implementations one at a time and then gone back and fixed the headers in one, smaller commit. If desired, I can go back and do it correctly... Otherwise, history is `make check` clean.

This is built off of #148 so once that's merged I'll rebase here.

### CODE REVIEW

**Comment by pbauman** [comment]
I don't know why the commits are in the order they are showing here. I have the correct order in my local `git log`...

**Comment by pbauman** [comment]
@roystgnr I ran this with VexCL and confirmed I didn't hose that. Anything else you think I should run this through before merging? We're effectively breaking backward compatibility here since we'll require linking to `libantioch`.

**Comment by roystgnr** [comment]
Compatibility breakage in the linker arguments doesn't bother me much.  :+1:

**Comment by ddemidov** [comment]
I am trying to look if travis is able to handle vexcl tests now: https://travis-ci.org/ddemidov/antioch/builds/67555027

**Comment by pbauman** [comment]
Thanks @ddemidov Looks like your test never even make it to `make check`... but it also didn't indicate why if failed. Just said job cancelled.

**Comment by ddemidov** [comment]
I amended the commit and cancelled the job. I hope I did everything right this time: https://travis-ci.org/ddemidov/antioch/jobs/67556457

**Comment by ddemidov** [comment]
Looks like there is still not enough memory :(

**Comment by pbauman** [comment]
:( Thanks for taking a look though!

**Comment by ddemidov** [comment]
Is it possible to disable specific tests based on environment variables (There is [TRAVIS=true](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) for example)?

**Comment by pbauman** [comment]
Hmmm, that's a good suggestion. I'm going to open a new ticket to post some ideas for discussion. In the mean time, I'll go ahead and merge this.

**Pull request merged**
