### PR TITLE
Bugfix for the ChemKin parser

### PR DESCRIPTION
**Pull request by SylvainPlessis**
This is the bugfix related to issue #165, it fixes for me the H2 values, this is what @beanSnippet remarked.  If you can verify before merging.

### CODE REVIEW

**Comment by SylvainPlessis** [comment]
So it seems that the bug was not the code, but my reading of ChemKin input files...   We actually already had a test for chemkin-read thermo, hopefully now, I have it all figured out.

**Comment by pbauman** [comment]
Could you squash those two commits, please?

**Comment by SylvainPlessis** [comment]
Also, we should probably cherry-pick it into the release, it's a pretty bad bug.

**Comment by pbauman** [comment]
Great minds think alike. :) Was going to suggest a 0.3.1 release. Will merge this into master and cherry pick from v0.3.0 and release v0.3.1 based on that.

I'll make ChemKin parser the focus of the unit testing after #164 is merged.

This will close #165.

**Pull request merged**
