### PR TITLE
Have Travis actually use Eigen when testing

### PR DESCRIPTION
**Pull request by pbauman**
It wasn't picking it up before, so let's point Antioch at it during Travis testing. @roystgnr mentioned failures with Eigen, so let's see if this picks them up.

### CODE REVIEW

**Comment by pbauman** [comment]
Dammit, looks like Ubuntu Precise uses Eigen 3.0.5-1 and we need >= 3.1.2 (at least, that's what configure says...).

**Comment by pbauman** [comment]
Looks like Trusty has Eigen 3.2.0-8. According to [this page](https://docs.travis-ci.com/user/trusty-ci-environment/), Travis has Trusty in Beta and we can opt-in. I'll push to this branch to at least try it out and then we can discuss whether we want to keep that or not.

**Comment by pbauman** [comment]
OK, I can squash the last two commits into 1. I'd be in favor of merging this, if only because we pick up Eigen testing in Travis. I feel like we're a pretty vanilla build here so that the "beta" part of the Trusty servers won't hit us so much. Thoughts @roystgnr, @SylvainPlessis?

**Comment by roystgnr** [comment]
:+1: after the squash

**Pull request merged**
