### PR TITLE
Remove deprecated CEAThermodynamics

### PR DESCRIPTION
**Pull request by pbauman**
Instead one should use CEAThermoMixture and CEAEvaluator. This has been deprecated 1.5 years. GRINS builds/passes tests with this branch. Time for this to go. `make check` passed locally on the laptop with Eigen and VexCL (with GCC 4.9.3, still get Eigen failures with GCC 5.3).

### CODE REVIEW

**Comment by roystgnr** [comment]
How are we getting Eigen failures triggered by *removing* code?  Are these failures that exist in master too?

**Comment by pbauman** [comment]
Sorry, I wasn't clear. I haven't been able to pass all checks at *any time* in the past or present with Eigen using GCC 5.3 (I'd mentioned this in previous PRs). I'm not sure if it's a compiler bug or Eigen's bug. I tried all Eigen versions back to 3.1.4 and I tried their 3.3 beta release. We get some nans on some tests. GCC 4.9.3 runs just fine. I haven't had a chance to try GCC 6.1.

Sorry for not making that clear. I'll open up an issue with some details.

**Comment by roystgnr** [comment]
:+1: then, thanks

**Comment by pbauman** [comment]
>  I haven't been able to pass all checks at any time in the past or present with Eigen using GCC 5.3 (I'd mentioned this in previous PRs). I'm not sure if it's a compiler bug or Eigen's bug. I tried all Eigen versions back to 3.1.4 and I tried their 3.3 beta release.

I'd been doing the Eigen+VexCL on the my (Mac) laptop. I just tried on my workstation and everything is fine... So apparently it's Mac-specific (even though I built the compiler myself using the same commands on each platform...). I'll open an issue just so we can track it.

**Comment by pbauman** [comment]
> I'd been doing the Eigen+VexCL on the my (Mac) laptop. I just tried on my workstation and everything is fine... So apparently it's Mac-specific (even though I built the compiler myself using the same commands on each platform...). I'll open an issue just so we can track it.

Crap. Now I can't reproduce it. Everything is working again...

**Pull request merged**
