### PR TITLE
Add Examples Directory to Antioch

### PR DESCRIPTION
**Pull request by nicholasmalaya**
This partially hits Numero seis on the todo list, 

<pre>
6. Add examples directory and example programs for usage. Kinetics, thermo, transport.
</pre>

I've added a directory, a makefile.AM, and a single example that builds and runs on my box. I would recommend we merge this guy, and then create a separate ticket that would populate the examples directories with representative cases of the kinetics, thermo and transport API access patterns. Wouldn't mind input from @roystgnr or @pbauman (or David Sondak, is he on github?) about what we might want to add in this case. Or we could look at Cantera and mimic the useful parts of those tests.

### CODE REVIEW

**Comment by variscarey** [comment]
Is the todo list somewhere on the github page or is this some internal
email?

Varis


On Wed, Jul 6, 2016 at 3:48 PM, Nicholas Malaya <notifications@github.com>
wrote:

> This partially hits Numero seis on the todo list,
>
> 6. Add examples directory and example programs for usage. Kinetics, thermo, transport.
>
> I've added a directory, a makefile.AM, and a single example that builds
> and runs on my box. I would recommend we merge this guy, and then create a
> separate ticket that would populate the examples directories with
> representative cases of the kinetics, thermo and transport API access
> patterns. Wouldn't mind input from @roystgnr <https://github.com/roystgnr>
> or @pbauman <https://github.com/pbauman> (or David Sondak, is he on
> github?) about what we might want to add in this case. Or we could look at
> Cantera and mimic the useful parts of those tests.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/libantioch/antioch/pull/218
> Commit Summary
>
>    - [antioch]: adding @nicholasmalaya to AUTHORS file
>    - [antioch]: adding header only and transport models to changelog
>    - Merge remote-tracking branch 'upstream/master'
>    - fixed a change i didnt want
>    - fixing things
>    - adding examples to build pattern
>    - adding makefile.am with representative example routine
>    - changing makefile.am, still not building
>    - adding examples to autoconf.ac directive
>    - adding example
>    - Merge branch 'examples_dir' of
>    https://github.com/nicholasmalaya/antioch into examples_dir
>    - fixing a mislabelled test
>    - compiles successfully, had stale elements in makefile.AM
>    - stealing an example from tests, test will compile and run on my box
>
> File Changes
>
>    - *M* AUTHORS
>    <https://github.com/libantioch/antioch/pull/218/files#diff-0> (8)
>    - *M* Makefile.am
>    <https://github.com/libantioch/antioch/pull/218/files#diff-1> (2)
>    - *M* configure.ac
>    <https://github.com/libantioch/antioch/pull/218/files#diff-2> (1)
>    - *A* examples/Makefile.am
>    <https://github.com/libantioch/antioch/pull/218/files#diff-3> (45)
>    - *A* examples/antioch_init.C
>    <https://github.com/libantioch/antioch/pull/218/files#diff-4> (102)
>
> Patch Links:
>
>    - https://github.com/libantioch/antioch/pull/218.patch
>    - https://github.com/libantioch/antioch/pull/218.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libantioch/antioch/pull/218>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGfn2QxxYL9JDnjlPeuUDabloGRYWtt5ks5qTCKygaJpZM4JGidC>
> .
>



-- 
Varis Carey
Assistant Professor
Department of Mathematical and Statistical Sciences
University of Colorado Denver

**Comment by hovr2pi** [comment]
Paul is in town today and tomorrow and we were all huddled up and doing a hack a thon.

Here is the relevant antioch list from the email Paul sent around.


Antioch:

1. More unit testing of �KineticsTheory� transport. As mentioned above, I was getting erroneous results with the Ozone flame with kinetics theory transport (IIRC, this manifest as temperature going unstable near where the reaction was starting). Also compare against Cantera output.
2. Move existing �standalone� unit tests to CppUnit-based tests.
3. Split out vibrational and electronic input into their own input files (for ASCII format).
4. Add vibrational/electronic species data parsing to XML format. Make sure there�s no cross-compatibility issues with Cantera.
5. Abandon parsing species molar mass and use elemental molar masses to sum up into species molar mass. This is what Cantera does and what we should be doing to more easily enable more complex species.
6. Add examples directory and example programs for usage. Kinetics, thermo, transport.
7. Add github.io website for Antioch and publish Doxygen documentation.
8. Get CI testing going on UB servers if Civet is open-sourced between now and then.
9. Populate more Blottner data based on fits to data (either the data roystgnr used the other day or, if we have confidence in our KineticsTheory implementation, use that).

**Comment by dmcdougall** [comment]
Added todo list [here](https://github.com/libantioch/antioch/issues/223).

**Comment by dmcdougall** [comment]
Clean history incoming.  Don't merge this.

**Comment by dmcdougall** [comment]
Replaced by #225.

**Pull request closed without merging**
