### PR TITLE
Clear Warnings

### PR DESCRIPTION
**Pull request by pbauman**
Clearing out some warnings I was hitting with GRINS. This may not be all of them yet because I'm not instantiating the new capabilities. Still have a couple -Woverloaded-virtual warnings to clear out, but will wait on #126 before finishing up. At least didn't want folks to duplicate effort.

### CODE REVIEW

**Comment by SylvainPlessis** [comment]
While you're at it, there is one that PINC hits, in the file _src/kinetics/.../constant_rate.h_, line 155, the parameter T is unused.

Thanks for doing this, I've been meaning to do it quite a long time ago...

**Comment by SylvainPlessis** [comment]
In _src/kinetics/include/antioch/reaction.h_, the methods ```compute_rate_of_progress_and_derivative``` (declared l. 265/277, defined l. 989/1156) contains a ```ChemicalMixture``` in their parameters' list.  This chemical mixture is quite old, it's odd we never hit it before, and is absolutely useless, both in the deprecated and new version.

We should at some point purely and simply delete it, thus modifying l. 285 of file _src/.../reaction_set.h_ where it is called.

Then there is a little bit more of hidden parameters is the parsers, I'll update the corresponding PR #131. 

Once this is done, PINC is alright with warnings from Antioch and I'm fully ok for merging.

**Comment by roystgnr** [comment]
Sylvain pointed out that we haven't merged this to master yet.  Paul, why'd you close #127 ?  Don't we want these fixes in both branches?

**Comment by pbauman** [comment]
Because we can manually merge to master. Will do so now.

**Pull request merged**
