### PR TITLE
Adding examples directory

### PR DESCRIPTION
**Pull request by dmcdougall**
Replaces #218.

### CODE REVIEW

**Comment by dmcdougall** [comment]
@nicholasmalaya Look ok?

**Comment by pbauman** [comment]
OK, let's add some examples (and make the existing "example" actually an example). Thanks @nicholasmalaya @dmcdougall

**Comment by roystgnr** [comment]
Anybody else failing "make install" with this?

```
Making install in examples
make[2]: Entering directory `/net/spark/workspace/roystgnr/git/antioch/normal/examples'
make[3]: Entering directory `/net/spark/workspace/roystgnr/git/antioch/normal/examples'
make[3]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '../../examples'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c antioch_init '../../examples'
Usage: /h2/roystgnr/git/antioch/normal/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: '../../examples' must be an absolute directory name
make[3]: *** [install-examplesPROGRAMS] Error 1
```

**Comment by roystgnr** [comment]
This is with a VPATH build.

**Pull request merged**
